services:
  - type: web
    name: sysmon-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/server.py
    envVars:
      - key: PORT
        value: "5000"
    autoDeploy: true
